//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: identity.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Identity_IdentityPBClient, then call methods of this protocol to make API calls.
internal protocol Identity_IdentityPBClientProtocol: GRPCClient {
  func retrieve(
    _ request: Identity_RetrieveRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Identity_RetrieveRequest, Identity_RetrieveReply>

}

extension Identity_IdentityPBClientProtocol {

  /// Unary call to retrieve
  ///
  /// - Parameters:
  ///   - request: Request to send to retrieve.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func retrieve(
    _ request: Identity_RetrieveRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Identity_RetrieveRequest, Identity_RetrieveReply> {
    return self.makeUnaryCall(
      path: "/identity.IdentityPB/retrieve",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class Identity_IdentityPBClient: Identity_IdentityPBClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the identity.IdentityPB service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

