//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: process.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Process_ProcessClient, then call methods of this protocol to make API calls.
internal protocol Process_ProcessClientProtocol: GRPCClient {
  func create(
    _ request: Process_CreateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Process_CreateRequest, Process_CreateReply>

}

extension Process_ProcessClientProtocol {

  /// Unary call to create
  ///
  /// - Parameters:
  ///   - request: Request to send to create.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func create(
    _ request: Process_CreateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Process_CreateRequest, Process_CreateReply> {
    return self.makeUnaryCall(
      path: "/process.Process/create",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class Process_ProcessClient: Process_ProcessClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the process.Process service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

